spring:
  application:
    name: user

---
spring:
  profiles: peer1
eureka:
  instance:
    metadataMap:
      zone: zone1
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/
server:
  port: ${PORT:8081}

zone:
  num: 1

---
spring:
  profiles: peer2
eureka:
  instance:
    metadataMap:
      zone: zone2
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8762/eureka/
server:
  port: ${PORT:8082}

zone:
  num: 2

---
spring:
  profiles: peer3
eureka:
  instance:
    metadataMap:
      zone: zone3
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8763/eureka/
server:
  port: ${PORT:8083}

zone:
  num: 3
