#server:
#    port: ${PORT:8761}
#    ssl:
#        key-store: classpath:localhost.p12
#        key-store-password: 123456
#        keyStoreType: PKCS12
#        keyAlias: client
#eureka:
#    client:
#        registerWithEureka: false
#        fetchRegistry: false
#    server:
#        enableSelfPreservation: false
#        evictionIntervalTimerInMs: 3000
spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: admin
    basic:
      enabled: true

---
spring:
    profiles: peer1
eureka:
    instance:
        hostname: peer1
        metadataMap:
            zone: zone1
    client:
        serviceUrl:
            defaultZone: http://admin:admin@localhost:8762/eureka/,http://admin:admin@localhost:8763/eureka/
server:
    port: ${PORT:8761}

---
spring:
    profiles: peer2
eureka:
    instance:
        hostname: peer2
        metadataMap:
            zone: zone2
    client:
        serviceUrl:
            defaultZone:  http://admin:admin@localhost:8761/eureka/,http://admin:admin@localhost:8763/eureka/
server:
    port: ${PORT:8762}
    
---
spring:
    profiles: peer3
eureka:
    instance:
        hostname: peer3
        metadataMap:
            zone: zone3
    client:
        serviceUrl:
            defaultZone:  http://admin:admin@localhost:8761/eureka/,http://admin:admin@localhost:8762/eureka/
server:
    port: ${PORT:8763}
